#
#Elite Botany Pot Speed
#Range: > 1
eliteBotanyPotSpeed = 2
#
#Ultra Botany Pot Speed
#Range: > 1
ultraBotanyPotSpeed = 4
#
#Creative Botany Pot Speed
#Range: > 1
creativeBotanyPotSpeed = 8
#
#Elite Botany Pot Multiplier
#Range: > 1
eliteBotanyPotMultiplier = 2
#
#Ultra Botany Pot Multiplier
#Range: > 1
ultraBotanyPotMultiplier = 4
#
#Creative Botany Pot Multiplier
#Range: > 1
creativeBotanyPotMultiplier = 8

