
[tier-mk1]
	#Modifies the processing time of taking to process a resource: 0 being no speed modifier and 1 being a single tick per resource
	#The way this works is by taking the processing time from the soil and crop, then dividing it by the value given here. 0 being 0% and 1 being 100%
	#Range: 0.0 ~ 1.0
	speedModifier = 0.23077
	#How much energy the pot will hold
	#Range: > 0
	maxEnergy = 50000
	#Energy consumed per tick
	#Range: > 0
	perTickEnergy = 50
	#Amount of items outputted per operation
	#Range: 1 ~ 1728
	itemsPerOutput = 2

[tier-mk2]
	#Modifies the processing time of taking to process a resource: 0 being no speed modifier and 1 being a single tick per resource
	#The way this works is by taking the processing time from the soil and crop, then dividing it by the value given here. 0 being 0% and 1 being 100%
	#Range: 0.0 ~ 1.0
	speedModifier = 0.5
	#How much energy the pot will hold
	#Range: > 0
	maxEnergy = 230000
	#Energy consumed per tick
	#Range: > 0
	perTickEnergy = 230
	#Amount of items outputted per operation
	#Range: 1 ~ 1728
	itemsPerOutput = 5

[tier-mk3]
	#Modifies the processing time of taking to process a resource: 0 being no speed modifier and 1 being a single tick per resource
	#The way this works is by taking the processing time from the soil and crop, then dividing it by the value given here. 0 being 0% and 1 being 100%
	#Range: 0.0 ~ 1.0
	speedModifier = 0.72973
	#How much energy the pot will hold
	#Range: > 0
	maxEnergy = 1600000
	#Energy consumed per tick
	#Range: > 0
	perTickEnergy = 1600
	#Amount of items outputted per operation
	#Range: 1 ~ 1728
	itemsPerOutput = 16

[tier-mk4]
	#Modifies the processing time of taking to process a resource: 0 being no speed modifier and 1 being a single tick per resource
	#The way this works is by taking the processing time from the soil and crop, then dividing it by the value given here. 0 being 0% and 1 being 100%
	#Range: 0.0 ~ 1.0
	speedModifier = 0.875
	#How much energy the pot will hold
	#Range: > 0
	maxEnergy = 16000000
	#Energy consumed per tick
	#Range: > 0
	perTickEnergy = 16000
	#Amount of items outputted per operation
	#Range: 1 ~ 1728
	itemsPerOutput = 64

