import crafttweaker.api.tag.MCTag;

//Ultimate Singularity

<tag:items:crafttweaker:singularities>.add(<item:extendedcrafting:singularity>);

mods.extendedcrafting.TableCrafting.remove(<item:extendedcrafting:ultimate_singularity>);
<recipetype:create:mechanical_crafting>.addRecipe("ultimate_singularity_custom", <item:extendedcrafting:ultimate_singularity>, [
	[<item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:extendedcrafting:singularity>.withTag({Id: "extendedcrafting:emerald" as string}), <item:extendedcrafting:singularity>.withTag({Id: "extendedcrafting:uranium" as string}), <item:extendedcrafting:singularity>.withTag({Id: "extendedcrafting:redstone" as string}), <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:minecraft:air>, <item:extendedcrafting:singularity>.withTag({Id: "extendedcrafting:diamond" as string}), <item:bigreactors:cyanite_ingot>, <item:extendedcrafting:nether_star_block>, <item:bigreactors:cyanite_ingot>, <item:extendedcrafting:singularity>.withTag({Id: "extendedcrafting:copper" as string}), <item:minecraft:air>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:extendedcrafting:singularity>.withTag({Id: "extendedcrafting:platinum" as string}), <item:enderioalloys:block_alloy_crystalline_pink_slime>, <item:naturesaura:sky_ingot>, <item:mysticalagradditions:creative_essence>, <item:naturesaura:sky_ingot>, <item:enderioalloys:block_alloy_stellar_alloy>, <item:extendedcrafting:singularity>.withTag({Id: "extendedcrafting:bronze" as string}), <item:minecraft:air>], 
	[<item:extendedcrafting:singularity>.withTag({Id: "extendedcrafting:quartz" as string}), <item:immersivepetroleum:petcoke>, <tag:items:forge:plastic>, <item:envirocore:xerothium>, <item:botania:gaia_ingot>, <item:extendedcrafting:enhanced_ender_ingot_block>, <item:bloodmagic:demonslate>, <item:immersiveengineering:logic_unit>, <item:extendedcrafting:singularity>.withTag({Id: "extendedcrafting:electrum" as string})], 
	[<item:extendedcrafting:singularity>.withTag({Id: "extendedcrafting:iron" as string}), <item:rftoolsbase:infused_diamond>, <item:mysticalagradditions:creative_essence>, <item:extendedcrafting:the_ultimate_block>, <item:draconicevolution:chaotic_core>, <item:extendedcrafting:the_ultimate_block>, <item:mysticalagradditions:creative_essence>, <item:rftoolsbase:infused_enderpearl>, <item:extendedcrafting:singularity>.withTag({Id: "extendedcrafting:glowstone" as string})], 
	[<item:extendedcrafting:singularity>.withTag({Id: "extendedcrafting:aluminum" as string}), <item:create:refined_radiance_casing>, <item:bloodmagic:demonslate>, <item:extendedcrafting:enhanced_ender_ingot_block>, <item:botania:gaia_ingot>, <item:envirocore:xerothium>, <tag:items:forge:plastic>, <item:create:shadow_steel_casing>, <item:extendedcrafting:singularity>.withTag({Id: "extendedcrafting:nickel" as string})], 
	[<item:minecraft:air>, <item:extendedcrafting:singularity>.withTag({Id: "extendedcrafting:silver" as string}), <item:enderioalloys:block_alloy_stellar_alloy>, <item:naturesaura:sky_ingot>, <item:mysticalagradditions:creative_essence>, <item:naturesaura:sky_ingot>, <item:enderioalloys:block_alloy_crystalline_pink_slime>, <item:extendedcrafting:singularity>.withTag({Id: "extendedcrafting:invar" as string}), <item:minecraft:air>], 
	[<item:minecraft:air>, <item:minecraft:air>, <item:extendedcrafting:singularity>.withTag({Id: "extendedcrafting:tin" as string}), <item:powah:steel_energized>, <item:extendedcrafting:nether_star_block>, <item:powah:steel_energized>, <item:extendedcrafting:singularity>.withTag({Id: "extendedcrafting:coal" as string}), <item:minecraft:air>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:extendedcrafting:singularity>.withTag({Id: "extendedcrafting:lapis_lazuli" as string}), <item:extendedcrafting:singularity>.withTag({Id: "extendedcrafting:lead" as string}), <item:extendedcrafting:singularity>.withTag({Id: "extendedcrafting:steel" as string}), <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>]
]);
mods.extendedcrafting.TableCrafting.addShapeless("the_ultimate_ingot", 0, <item:extendedcrafting:the_ultimate_ingot>, [
	<item:minecraft:iron_ingot>, <item:minecraft:gold_ingot>, <item:minecraft:netherite_ingot>, <item:extendedcrafting:ender_ingot>, <item:extendedcrafting:enhanced_ender_ingot>, <item:extendedcrafting:crystaltine_ingot>, <item:extendedcrafting:redstone_ingot>, <item:extendedcrafting:black_iron_ingot>, <item:silents_mechanisms:redstone_alloy_ingot>,
        <item:woot:si_ingot>, <item:silents_mechanisms:compressed_iron_ingot>, <tag:items:forge:ingots/copper>, <tag:items:forge:ingots/tin>, <tag:items:forge:ingots/silver>, <tag:items:forge:ingots/lead>, <tag:items:forge:ingots/nickel>, <item:silents_mechanisms:platinum_ingot>, <tag:items:forge:ingots/zinc>,
        <item:silents_mechanisms:bismuth_ingot>, <tag:items:forge:ingots/aluminum>, <tag:items:forge:ingots/uranium>, <tag:items:forge:ingots/bronze>, <tag:items:forge:ingots/brass>, <tag:items:forge:ingots/invar>, <tag:items:forge:ingots/electrum>, <tag:items:forge:ingots/steel>, <item:silents_mechanisms:bismuth_brass_ingot>,
        <item:silents_mechanisms:aluminum_steel_ingot>, <item:silents_mechanisms:bismuth_steel_ingot>, <tag:items:forge:ingots/signalum>, <tag:items:forge:ingots/lumium>, <tag:items:forge:ingots/enderium>, <item:industrialforegoing:pink_slime_ingot>, <item:silentgear:crimson_iron_ingot>, <item:silentgear:crimson_steel_ingot>, <item:silentgear:blaze_gold_ingot>,
        <item:silentgear:azure_silver_ingot>, <item:silentgear:azure_electrum_ingot>, <item:silentgear:tyrian_steel_ingot>, <item:botania:manasteel_ingot>, <item:botania:terrasteel_ingot>, <item:botania:elementium_ingot>, <item:silents_mechanisms:refined_iron_ingot>, <item:mekanism:ingot_refined_obsidian>, <item:mekanism:ingot_refined_glowstone>,
        <tag:items:forge:ingots/osmium>, <tag:items:forge:ingots/cobalt>, <item:tconstruct:slimesteel_ingot>, <item:tconstruct:tinkers_bronze_ingot>, <item:tconstruct:rose_gold_ingot>, <item:tconstruct:pig_iron_ingot>, <item:tconstruct:queens_slime_ingot>, <item:tconstruct:manyullyn_ingot>, <item:tconstruct:hepatizon_ingot>, 
        <tag:items:forge:ingots/constantan>, <item:lazierae2:fluix_steel_ingot>, <item:refinedstorage:quartz_enriched_iron>, <item:enderioalloys:item_alloy_ingot_conductive_iron>, <item:enderioalloys:item_alloy_ingot_redstone_alloy>, <item:enderioalloys:item_alloy_ingot_pulsating_iron>, <item:enderioalloys:item_alloy_ingot_electrical_steel>, <item:enderioalloys:item_alloy_ingot_dark_steel>, <item:enderioalloys:item_alloy_ingot_end_steel>,
        <item:enderioalloys:item_alloy_ingot_energetic_alloy>, <item:enderioalloys:item_alloy_ingot_vibrant_alloy>, <item:enderioalloys:item_alloy_ingot_soularium>, <item:enderioalloys:item_material_glazed_nether_brick>, <item:naturesaura:infused_iron>, <item:naturesaura:tainted_gold>, <item:naturesaura:sky_ingot>, <item:immersiveengineering:ingot_hop_graphite>, <item:powah:steel_energized>,
        <item:bigreactors:cyanite_ingot>, <item:projectred-core:electrotine_ingot>, <item:enderioalloys:item_alloy_ingot_crude_steel>, <item:enderioalloys:item_alloy_ingot_crystalline_alloy>, <item:enderioalloys:item_alloy_ingot_melodic_alloy>, <item:enderioalloys:item_alloy_ingot_stellar_alloy>, <item:enderioalloys:item_alloy_ingot_crystalline_pink_slime>, <item:enderioalloys:item_alloy_ingot_energetic_silver>, <item:enderioalloys:item_alloy_ingot_vivid_alloy>
]);
mods.extendedcrafting.TableCrafting.addShaped("creative_essence", 0, <item:mysticalagradditions:creative_essence>, [
	[<item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>],
	[<item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:nether_star>, <item:minecraft:air>, <item:minecraft:nether_star>, <item:minecraft:air>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:minecraft:nether_star>, <item:minecraft:air>, <item:minecraft:nether_star>, <item:mysticalagradditions:insanium_essence>, <item:minecraft:nether_star>, <item:mysticalagradditions:insanium_essence>, <item:minecraft:nether_star>, <item:minecraft:air>], 
	[<item:minecraft:nether_star>, <item:mysticalagradditions:insanium_essence>, <item:minecraft:nether_star>, <item:mysticalagradditions:insanium_essence>, <item:mysticalagradditions:insanium_essence>, <item:minecraft:nether_star>, <item:mysticalagradditions:insanium_essence>, <item:mysticalagradditions:insanium_essence>, <item:minecraft:nether_star>], 
	[<item:minecraft:nether_star>, <item:mysticalagradditions:insanium_essence>, <item:mysticalagradditions:insanium_essence>, <item:mysticalagradditions:insanium_essence>, <item:mysticalagradditions:insanium_essence>, <item:mysticalagradditions:insanium_essence>, <item:mysticalagradditions:insanium_essence>, <item:mysticalagradditions:insanium_essence>, <item:minecraft:nether_star>], 
	[<item:minecraft:nether_star>, <item:mysticalagradditions:insanium_essence>, <item:mysticalagradditions:insanium_essence>, <item:mysticalagradditions:insanium_essence>, <item:mysticalagradditions:insanium_essence>, <item:mysticalagradditions:insanium_essence>, <item:mysticalagradditions:insanium_essence>, <item:mysticalagradditions:insanium_essence>, <item:minecraft:nether_star>], 
	[<item:minecraft:air>, <item:minecraft:nether_star>, <item:mysticalagradditions:insanium_essence>, <item:mysticalagradditions:insanium_essence>, <item:mysticalagradditions:insanium_essence>, <item:mysticalagradditions:insanium_essence>, <item:mysticalagradditions:insanium_essence>, <item:minecraft:nether_star>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:minecraft:air>, <item:minecraft:nether_star>, <item:mysticalagradditions:insanium_essence>, <item:mysticalagradditions:insanium_essence>, <item:mysticalagradditions:insanium_essence>, <item:minecraft:nether_star>, <item:minecraft:air>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:nether_star>, <item:minecraft:nether_star>, <item:minecraft:nether_star>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>]
]);

//Extended Crafting
craftingTable.removeByName("extendedcrafting:ender_crafter");
craftingTable.addShaped("ender_crafter_custom", <item:extendedcrafting:ender_crafter>, [
	[<item:minecraft:ender_eye>, <item:minecraft:ender_eye>, <item:minecraft:ender_eye>], 
	[<item:extendedcrafting:ender_ingot>, <item:minecraft:crafting_table>, <item:extendedcrafting:ender_ingot>], 
	[<tag:items:forge:ingots/enderium>, <tag:items:forge:ingots/enderium>, <tag:items:forge:ingots/enderium>]
]);
craftingTable.removeByName("extendedcrafting:ender_alternator");
craftingTable.addShaped("ender_alternator_custom", <item:extendedcrafting:ender_alternator> * 2, [
	[<item:minecraft:air>, <item:minecraft:ender_eye>, <item:minecraft:air>], 
	[<item:minecraft:air>, <tag:items:forge:ingots/enderium>, <item:minecraft:air>], 
	[<item:extendedcrafting:ender_ingot>, <tag:items:forge:ingots/enderium>, <item:extendedcrafting:ender_ingot>]
]);
craftingTable.removeByName("extendedcrafting:luminessence");
mods.extendedcrafting.EnderCrafting.addShapeless("luminessence_custom", <item:extendedcrafting:luminessence>, [
	<item:minecraft:yellow_dye>, <item:minecraft:yellow_dye>, <item:minecraft:gold_ingot>, 
	<item:minecraft:yellow_dye>, <item:minecraft:gold_ingot>, <item:minecraft:gold_ingot>, 
	<item:minecraft:redstone>, <item:minecraft:redstone>, <item:minecraft:gunpowder>
], 10);
craftingTable.removeByName("extendedcrafting:basic_table");
mods.extendedcrafting.CombinationCrafting.addRecipe("basic_table_custom", <item:extendedcrafting:basic_table>, 50000, [
	<item:extendedcrafting:basic_catalyst>, <item:extendedcrafting:basic_component>, <item:extendedcrafting:basic_component>, <item:minecraft:crafting_table>, <item:minecraft:iron_block>, <item:extendedcrafting:basic_component>, <item:extendedcrafting:basic_component>, <item:minecraft:iron_block>, <item:minecraft:crafting_table>
]);
craftingTable.removeByName("extendedcrafting:advanced_table");
mods.extendedcrafting.CombinationCrafting.addRecipe("advanced_table_custom", <item:extendedcrafting:advanced_table>, 100000, [
	<item:extendedcrafting:advanced_catalyst>, <item:extendedcrafting:basic_table>, <item:extendedcrafting:advanced_component>, <item:minecraft:gold_block>, <item:extendedcrafting:advanced_component>, <item:extendedcrafting:advanced_component>, <item:extendedcrafting:basic_table>, <item:minecraft:gold_block>, <item:extendedcrafting:advanced_component>
]);
craftingTable.removeByName("extendedcrafting:elite_table");
mods.extendedcrafting.CombinationCrafting.addRecipe("elite_table_custom", <item:extendedcrafting:elite_table>, 150000, [
	<item:extendedcrafting:elite_catalyst>, <item:extendedcrafting:elite_component>, <item:extendedcrafting:elite_component>, <item:extendedcrafting:advanced_table>, <item:minecraft:diamond_block>, <item:extendedcrafting:elite_component>, <item:extendedcrafting:elite_component>, <item:minecraft:diamond_block>, <item:extendedcrafting:advanced_table>
]);
craftingTable.removeByName("extendedcrafting:ultimate_table");
mods.extendedcrafting.CombinationCrafting.addRecipe("ultimate_table_custom", <item:extendedcrafting:ultimate_table>, 200000, [
	<item:extendedcrafting:ultimate_catalyst>, <item:extendedcrafting:ultimate_component>, <item:extendedcrafting:ultimate_component>, <item:extendedcrafting:elite_table>, <item:minecraft:emerald_block>, <item:extendedcrafting:ultimate_component>, <item:extendedcrafting:ultimate_component>, <item:minecraft:emerald_block>, <item:extendedcrafting:elite_table>
]);


//creative Items
<tag:items:crafttweaker:infinity_cards>.add(<item:rsinfinitybooster:infinity_card>);
<tag:items:crafttweaker:dimension_cards>.add(<item:ae2wtlib:infinity_booster_card>,<item:rsinfinitybooster:dimension_card>);
<tag:items:crafttweaker:wireless_range_boosters>.add(<item:refinedstorage:range_upgrade>,<item:appliedenergistics2:wireless_booster>);

mods.extendedcrafting.TableCrafting.addShaped("creative_fluid_tank", 0, <item:mekanism:creative_fluid_tank>, [
	[<item:mekanismgenerators:fusion_reactor_frame>, <item:mekanismgenerators:reactor_glass>, <item:mekanismgenerators:reactor_glass>, <item:mekanismgenerators:reactor_glass>, <item:mekanismgenerators:reactor_glass>, <item:mekanismgenerators:reactor_glass>, <item:mekanismgenerators:reactor_glass>, <item:mekanismgenerators:reactor_glass>, <item:mekanismgenerators:fusion_reactor_frame>], 
	[<item:mekanismgenerators:reactor_glass>, <item:mekanismgenerators:fusion_reactor_frame>, <tag:items:refinedstorage:disks/fluids/1048576k>, <item:mekanism:ultimate_mechanical_pipe>, <item:industrialforegoing:black_hole_controller>, <item:mekanism:ultimate_mechanical_pipe>, <tag:items:refinedstorage:disks/fluids/1048576k>, <item:mekanismgenerators:fusion_reactor_frame>, <item:mekanismgenerators:reactor_glass>], 
	[<item:mekanismgenerators:reactor_glass>, <tag:items:refinedstorage:disks/fluids/1048576k>, <item:mekanism:ultimate_fluid_tank>, <item:mekanism:dynamic_tank>, <item:extendedcrafting:crystaltine_catalyst>, <item:mekanism:dynamic_tank>, <item:mekanism:ultimate_fluid_tank>, <tag:items:refinedstorage:disks/fluids/1048576k>, <item:mekanismgenerators:reactor_glass>], 
	[<item:mekanismgenerators:reactor_glass>, <item:mekanism:ultimate_mechanical_pipe>, <item:mekanism:dynamic_tank>, <item:extendedcrafting:the_ultimate_ingot>, <item:storagedrawers:creative_storage_upgrade>, <item:mysticalagradditions:creative_essence>, <item:mekanism:dynamic_tank>, <item:mekanism:ultimate_mechanical_pipe>, <item:mekanismgenerators:reactor_glass>], 
	[<item:mekanismgenerators:reactor_glass>, <item:industrialforegoing:supreme_black_hole_tank>, <item:minecraft:netherite_ingot>, <item:storagedrawers:creative_storage_upgrade>, <item:extendedcrafting:ultimate_singularity>, <item:storagedrawers:creative_storage_upgrade>, <item:minecraft:netherite_ingot>, <item:industrialforegoing:supreme_black_hole_tank>, <item:mekanismgenerators:reactor_glass>], 
	[<item:mekanismgenerators:reactor_glass>, <item:mekanism:ultimate_mechanical_pipe>, <item:mekanism:dynamic_tank>, <item:mysticalagradditions:creative_essence>, <item:storagedrawers:creative_storage_upgrade>, <item:extendedcrafting:the_ultimate_ingot>, <item:mekanism:dynamic_tank>, <item:mekanism:ultimate_mechanical_pipe>, <item:mekanismgenerators:reactor_glass>], 
	[<item:mekanismgenerators:reactor_glass>, <tag:items:refinedstorage:disks/fluids/1048576k>, <item:mekanism:ultimate_fluid_tank>, <item:mekanism:dynamic_tank>, <item:extendedcrafting:crystaltine_catalyst>, <item:mekanism:dynamic_tank>, <item:mekanism:ultimate_fluid_tank>, <tag:items:refinedstorage:disks/fluids/1048576k>, <item:mekanismgenerators:reactor_glass>], 
	[<item:mekanismgenerators:reactor_glass>, <item:mekanismgenerators:fusion_reactor_frame>, <tag:items:refinedstorage:disks/fluids/1048576k>, <item:mekanism:ultimate_mechanical_pipe>, <item:industrialforegoing:supreme_black_hole_tank>, <item:mekanism:ultimate_mechanical_pipe>, <tag:items:refinedstorage:disks/fluids/1048576k>, <item:mekanismgenerators:fusion_reactor_frame>, <item:mekanismgenerators:reactor_glass>], 
	[<item:mekanismgenerators:fusion_reactor_frame>, <item:mekanismgenerators:reactor_glass>, <item:mekanismgenerators:reactor_glass>, <item:mekanismgenerators:reactor_glass>, <item:mekanismgenerators:reactor_glass>, <item:mekanismgenerators:reactor_glass>, <item:mekanismgenerators:reactor_glass>, <item:mekanismgenerators:reactor_glass>, <item:mekanismgenerators:fusion_reactor_frame>]
]);
craftingTable.addShapeless("create_to_mekanism.creative_fluid_tank", <item:mekanism:creative_fluid_tank>, [
	<item:create:creative_fluid_tank>
]);
craftingTable.addShapeless("mekanism_to_create.creative_fluid_tank", <item:create:creative_fluid_tank>, [
	<item:mekanism:creative_fluid_tank>
]);
mods.extendedcrafting.TableCrafting.addShaped("creative_chemical_tank", 0, <item:mekanism:creative_chemical_tank>, [
	[<item:mekanismgenerators:fusion_reactor_frame>, <item:mekanismgenerators:fusion_reactor_frame>, <item:mekanismgenerators:reactor_glass>, <item:mekanismgenerators:reactor_glass>, <item:compressium:redstone_1>, <item:mekanismgenerators:reactor_glass>, <item:mekanismgenerators:reactor_glass>, <item:mekanismgenerators:fusion_reactor_frame>, <item:mekanismgenerators:fusion_reactor_frame>], 
	[<item:mekanismgenerators:fusion_reactor_frame>, <item:mekanismgenerators:fusion_reactor_frame>, <tag:items:forge:storage_blocks/osmium>, <item:mekanism:ultimate_pressurized_tube>, <item:industrialforegoing:black_hole_controller>, <item:mekanism:ultimate_pressurized_tube>, <tag:items:forge:storage_blocks/osmium>, <item:mekanismgenerators:fusion_reactor_frame>, <item:mekanismgenerators:fusion_reactor_frame>], 
	[<item:mekanismgenerators:reactor_glass>, <tag:items:forge:storage_blocks/osmium>, <item:mekanism:ultimate_chemical_tank>, <item:mekanism:dynamic_tank>, <item:extendedcrafting:crystaltine_catalyst>, <item:mekanism:dynamic_tank>, <item:mekanism:ultimate_chemical_tank>, <tag:items:forge:storage_blocks/osmium>, <item:mekanismgenerators:reactor_glass>], 
	[<item:mekanismgenerators:reactor_glass>, <item:mekanism:ultimate_pressurized_tube>, <item:mekanism:dynamic_tank>, <item:extendedcrafting:the_ultimate_ingot>, <item:storagedrawers:creative_storage_upgrade>, <item:mysticalagradditions:creative_essence>, <item:mekanism:dynamic_tank>, <item:mekanism:ultimate_pressurized_tube>, <item:mekanismgenerators:reactor_glass>], 
	[<item:compressium:redstone_1>, <item:mekanism:ultimate_chemical_tank>, <item:minecraft:netherite_ingot>, <item:storagedrawers:creative_storage_upgrade>, <item:extendedcrafting:ultimate_singularity>, <item:storagedrawers:creative_storage_upgrade>, <item:minecraft:netherite_ingot>, <item:mekanism:ultimate_chemical_tank>, <item:compressium:redstone_1>], 
	[<item:mekanismgenerators:reactor_glass>, <item:mekanism:ultimate_pressurized_tube>, <item:mekanism:dynamic_tank>, <item:mysticalagradditions:creative_essence>, <item:storagedrawers:creative_storage_upgrade>, <item:extendedcrafting:the_ultimate_ingot>, <item:mekanism:dynamic_tank>, <item:mekanism:ultimate_pressurized_tube>, <item:mekanismgenerators:reactor_glass>], 
	[<item:mekanismgenerators:reactor_glass>, <tag:items:forge:storage_blocks/osmium>, <item:mekanism:ultimate_chemical_tank>, <item:mekanism:dynamic_tank>, <item:extendedcrafting:crystaltine_catalyst>, <item:mekanism:dynamic_tank>, <item:mekanism:ultimate_chemical_tank>, <tag:items:forge:storage_blocks/osmium>, <item:mekanismgenerators:reactor_glass>], 
	[<item:mekanismgenerators:fusion_reactor_frame>, <item:mekanismgenerators:fusion_reactor_frame>, <tag:items:forge:storage_blocks/osmium>, <item:mekanism:ultimate_pressurized_tube>, <item:mekanism:ultimate_chemical_tank>, <item:mekanism:ultimate_pressurized_tube>, <tag:items:forge:storage_blocks/osmium>, <item:mekanismgenerators:fusion_reactor_frame>, <item:mekanismgenerators:fusion_reactor_frame>], 
	[<item:mekanismgenerators:fusion_reactor_frame>, <item:mekanismgenerators:fusion_reactor_frame>, <item:mekanismgenerators:reactor_glass>, <item:mekanismgenerators:reactor_glass>, <item:compressium:redstone_1>, <item:mekanismgenerators:reactor_glass>, <item:mekanismgenerators:reactor_glass>, <item:mekanismgenerators:fusion_reactor_frame>, <item:mekanismgenerators:fusion_reactor_frame>]
]);
mods.extendedcrafting.TableCrafting.addShaped("creative_energy_cube", 0, <item:mekanism:creative_energy_cube>.withTag({mekData: {EnergyContainers: [{Container: 0 as byte, stored: "18446744073709551615.9999" as string}]}}), [
	[<item:mekanismgenerators:fusion_reactor_frame>, <item:mekanismgenerators:fusion_reactor_frame>, <item:mekanismgenerators:reactor_glass>, <item:mekanismgenerators:reactor_glass>, <item:mekanismgenerators:fusion_reactor_port>, <item:mekanismgenerators:reactor_glass>, <item:mekanismgenerators:reactor_glass>, <item:mekanismgenerators:fusion_reactor_frame>, <item:mekanismgenerators:fusion_reactor_frame>], 
	[<item:mekanismgenerators:fusion_reactor_frame>, <item:mekanism:ultimate_energy_cube>.withTag({mekData: {EnergyContainers: [{Container: 0 as byte, stored: "256000000" as string}]}}), <item:mekanism:ultimate_induction_cell>, <item:solarflux:sp_de.chaotic>, <item:fluxnetworks:gargantuan_flux_storage>, <item:solarflux:sp_de.chaotic>, <item:mekanism:ultimate_induction_cell>, <item:mekanism:ultimate_energy_cube>.withTag({mekData: {EnergyContainers: [{Container: 0 as byte, stored: "256000000" as string}]}}), <item:mekanismgenerators:fusion_reactor_frame>], 
	[<item:mekanismgenerators:reactor_glass>, <item:mekanism:ultimate_induction_cell>, <item:powah:energy_cell_nitro>, <item:extendedcrafting:the_ultimate_ingot>, <item:mysticalagradditions:creative_essence>, <item:extendedcrafting:the_ultimate_ingot>, <item:powah:energy_cell_nitro>, <item:mekanism:ultimate_induction_cell>, <item:mekanismgenerators:reactor_glass>], 
	[<item:mekanismgenerators:reactor_glass>, <item:solarflux:sp_de.chaotic>, <item:extendedcrafting:the_ultimate_ingot>, <item:powah:solar_panel_nitro>, <item:mekanism:ultimate_universal_cable>, <item:powah:solar_panel_nitro>, <item:extendedcrafting:the_ultimate_ingot>, <item:solarflux:sp_de.chaotic>, <item:mekanismgenerators:reactor_glass>], 
	[<item:mekanismgenerators:fusion_reactor_port>, <item:fluxnetworks:gargantuan_flux_storage>, <item:mysticalagradditions:creative_essence>, <item:mekanism:ultimate_universal_cable>, <item:extendedcrafting:ultimate_singularity>, <item:mekanism:ultimate_universal_cable>, <item:mysticalagradditions:creative_essence>, <item:fluxnetworks:gargantuan_flux_storage>, <item:mekanismgenerators:fusion_reactor_port>], 
	[<item:mekanismgenerators:reactor_glass>, <item:solarflux:sp_de.chaotic>, <item:extendedcrafting:the_ultimate_ingot>, <item:powah:solar_panel_nitro>, <item:mekanism:ultimate_universal_cable>, <item:powah:solar_panel_nitro>, <item:extendedcrafting:the_ultimate_ingot>, <item:solarflux:sp_de.chaotic>, <item:mekanismgenerators:reactor_glass>], 
	[<item:mekanismgenerators:reactor_glass>, <item:mekanism:ultimate_induction_cell>, <item:powah:energy_cell_nitro>, <item:extendedcrafting:the_ultimate_ingot>, <item:mysticalagradditions:creative_essence>, <item:extendedcrafting:the_ultimate_ingot>, <item:powah:energy_cell_nitro>, <item:mekanism:ultimate_induction_cell>, <item:mekanismgenerators:reactor_glass>], 
	[<item:mekanismgenerators:fusion_reactor_frame>, <item:mekanism:ultimate_energy_cube>.withTag({mekData: {EnergyContainers: [{Container: 0 as byte, stored: "256000000" as string}]}}), <item:mekanism:ultimate_induction_cell>, <item:solarflux:sp_de.chaotic>, <item:fluxnetworks:gargantuan_flux_storage>, <item:solarflux:sp_de.chaotic>, <item:mekanism:ultimate_induction_cell>, <item:mekanism:ultimate_energy_cube>.withTag({mekData: {EnergyContainers: [{Container: 0 as byte, stored: "256000000" as string}]}}), <item:mekanismgenerators:fusion_reactor_frame>], 
	[<item:mekanismgenerators:fusion_reactor_frame>, <item:mekanismgenerators:fusion_reactor_frame>, <item:mekanismgenerators:reactor_glass>, <item:mekanismgenerators:reactor_glass>, <item:mekanismgenerators:fusion_reactor_port>, <item:mekanismgenerators:reactor_glass>, <item:mekanismgenerators:reactor_glass>, <item:mekanismgenerators:fusion_reactor_frame>, <item:mekanismgenerators:fusion_reactor_frame>]
]);
craftingTable.removeByName("creativecrafter:creative_crafter");
mods.extendedcrafting.TableCrafting.addShaped("creative_crafter_custom", 0, <item:creativecrafter:creative_crafter>, [
	[<item:refinedstorage:crafting_upgrade>, <item:refinedstorage:crafting_upgrade>, <item:refinedstorage:crafting_upgrade>, <item:refinedstorage:crafting_upgrade>, <item:refinedstorage:controller>, <item:refinedstorage:crafting_upgrade>, <item:refinedstorage:crafting_upgrade>, <item:refinedstorage:crafting_upgrade>, <item:refinedstorage:crafting_upgrade>], 
	[<item:refinedstorage:crafting_upgrade>, <item:mekanismgenerators:fusion_reactor_frame>, <item:extendedcrafting:the_ultimate_ingot>, <item:refinedstorage:machine_casing>, <item:refinedstorage:speed_upgrade>, <item:refinedstorage:machine_casing>, <item:extendedcrafting:the_ultimate_ingot>, <item:mekanismgenerators:fusion_reactor_frame>, <item:refinedstorage:crafting_upgrade>], 
	[<item:refinedstorage:crafting_upgrade>, <item:extendedcrafting:the_ultimate_ingot>, <item:refinedstorage:machine_casing>, <item:refinedstorage:speed_upgrade>, <item:refinedstorage:stack_upgrade>, <item:refinedstorage:speed_upgrade>, <item:refinedstorage:machine_casing>, <item:extendedcrafting:the_ultimate_ingot>, <item:refinedstorage:crafting_upgrade>], 
	[<item:refinedstorage:crafting_upgrade>, <item:refinedstorage:machine_casing>, <item:refinedstorage:speed_upgrade>, <item:refinedstorage:stack_upgrade>, <item:extrastorage:netherite_crafter>, <item:refinedstorage:stack_upgrade>, <item:refinedstorage:speed_upgrade>, <item:refinedstorage:machine_casing>, <item:refinedstorage:crafting_upgrade>], 
	[<item:refinedstorage:controller>, <item:refinedstorage:speed_upgrade>, <item:refinedstorage:stack_upgrade>, <item:extrastorage:netherite_crafter>, <item:extendedcrafting:ultimate_singularity>, <item:extrastorage:netherite_crafter>, <item:refinedstorage:stack_upgrade>, <item:refinedstorage:speed_upgrade>, <item:refinedstorage:controller>], 
	[<item:refinedstorage:crafting_upgrade>, <item:refinedstorage:machine_casing>, <item:refinedstorage:speed_upgrade>, <item:refinedstorage:stack_upgrade>, <item:extrastorage:netherite_crafter>, <item:refinedstorage:stack_upgrade>, <item:refinedstorage:speed_upgrade>, <item:refinedstorage:machine_casing>, <item:refinedstorage:crafting_upgrade>], 
	[<item:refinedstorage:crafting_upgrade>, <item:extendedcrafting:the_ultimate_ingot>, <item:refinedstorage:machine_casing>, <item:refinedstorage:speed_upgrade>, <item:refinedstorage:stack_upgrade>, <item:refinedstorage:speed_upgrade>, <item:refinedstorage:machine_casing>, <item:extendedcrafting:the_ultimate_ingot>, <item:refinedstorage:crafting_upgrade>], 
	[<item:refinedstorage:crafting_upgrade>, <item:mekanismgenerators:fusion_reactor_frame>, <item:extendedcrafting:the_ultimate_ingot>, <item:refinedstorage:machine_casing>, <item:refinedstorage:speed_upgrade>, <item:refinedstorage:machine_casing>, <item:extendedcrafting:the_ultimate_ingot>, <item:mekanismgenerators:fusion_reactor_frame>, <item:refinedstorage:crafting_upgrade>], 
	[<item:refinedstorage:crafting_upgrade>, <item:refinedstorage:crafting_upgrade>, <item:refinedstorage:crafting_upgrade>, <item:refinedstorage:crafting_upgrade>, <item:refinedstorage:controller>, <item:refinedstorage:crafting_upgrade>, <item:refinedstorage:crafting_upgrade>, <item:refinedstorage:crafting_upgrade>, <item:refinedstorage:crafting_upgrade>]
]);
mods.extendedcrafting.TableCrafting.addShaped("creative_storage_upgrade", 0, <item:storagedrawers:creative_storage_upgrade>, [
	[<item:storagedrawers:void_upgrade>, <item:storagedrawers:emerald_storage_upgrade>, <item:storagedrawers:emerald_storage_upgrade>, <item:storagedrawers:emerald_storage_upgrade>, <item:storagedrawers:emerald_storage_upgrade>, <item:storagedrawers:emerald_storage_upgrade>, <item:storagedrawers:emerald_storage_upgrade>, <item:storagedrawers:emerald_storage_upgrade>, <item:storagedrawers:void_upgrade>], 
	[<item:storagedrawers:emerald_storage_upgrade>, <tag:items:storagedrawers:drawers>, <tag:items:storagedrawers:drawers>, <tag:items:storagedrawers:drawers>, <tag:items:storagedrawers:drawers>, <tag:items:storagedrawers:drawers>, <tag:items:storagedrawers:drawers>, <tag:items:storagedrawers:drawers>, <item:storagedrawers:emerald_storage_upgrade>], 
	[<item:storagedrawers:emerald_storage_upgrade>, <tag:items:storagedrawers:drawers>, <item:extendedcrafting:the_ultimate_ingot>, <item:extendedcrafting:the_ultimate_ingot>, <item:extendedcrafting:the_ultimate_ingot>, <item:extendedcrafting:the_ultimate_ingot>, <item:extendedcrafting:the_ultimate_ingot>, <tag:items:storagedrawers:drawers>, <item:storagedrawers:emerald_storage_upgrade>], 
	[<item:storagedrawers:emerald_storage_upgrade>, <tag:items:storagedrawers:drawers>, <item:extendedcrafting:the_ultimate_ingot>, <item:mysticalagradditions:creative_essence>, <tag:items:refinedstorage:disks/items/16384k>, <item:mysticalagradditions:creative_essence>, <item:extendedcrafting:the_ultimate_ingot>, <tag:items:storagedrawers:drawers>, <item:storagedrawers:emerald_storage_upgrade>], 
	[<item:storagedrawers:emerald_storage_upgrade>, <tag:items:storagedrawers:drawers>, <item:extendedcrafting:the_ultimate_ingot>, <tag:items:refinedstorage:disks/items/16384k>, <item:extendedcrafting:ultimate_singularity>, <tag:items:refinedstorage:disks/items/16384k>, <item:extendedcrafting:the_ultimate_ingot>, <tag:items:storagedrawers:drawers>, <item:storagedrawers:emerald_storage_upgrade>], 
	[<item:storagedrawers:emerald_storage_upgrade>, <tag:items:storagedrawers:drawers>, <item:extendedcrafting:the_ultimate_ingot>, <item:mysticalagradditions:creative_essence>, <tag:items:refinedstorage:disks/items/16384k>, <item:mysticalagradditions:creative_essence>, <item:extendedcrafting:the_ultimate_ingot>, <tag:items:storagedrawers:drawers>, <item:storagedrawers:emerald_storage_upgrade>], 
	[<item:storagedrawers:emerald_storage_upgrade>, <tag:items:storagedrawers:drawers>, <item:extendedcrafting:the_ultimate_ingot>, <item:extendedcrafting:the_ultimate_ingot>, <item:extendedcrafting:the_ultimate_ingot>, <item:extendedcrafting:the_ultimate_ingot>, <item:extendedcrafting:the_ultimate_ingot>, <tag:items:storagedrawers:drawers>, <item:storagedrawers:emerald_storage_upgrade>], 
	[<item:storagedrawers:emerald_storage_upgrade>, <tag:items:storagedrawers:drawers>, <tag:items:storagedrawers:drawers>, <tag:items:storagedrawers:drawers>, <tag:items:storagedrawers:drawers>, <tag:items:storagedrawers:drawers>, <tag:items:storagedrawers:drawers>, <tag:items:storagedrawers:drawers>, <item:storagedrawers:emerald_storage_upgrade>], 
	[<item:storagedrawers:void_upgrade>, <item:storagedrawers:emerald_storage_upgrade>, <item:storagedrawers:emerald_storage_upgrade>, <item:storagedrawers:emerald_storage_upgrade>, <item:storagedrawers:emerald_storage_upgrade>, <item:storagedrawers:emerald_storage_upgrade>, <item:storagedrawers:emerald_storage_upgrade>, <item:storagedrawers:emerald_storage_upgrade>, <item:storagedrawers:void_upgrade>]
]);
mods.extendedcrafting.TableCrafting.addShaped("infinite_storage_disk_custom", 0, <item:refinedstorage:creative_storage_disk>, [
	[<item:extrastorage:neural_processor>, <item:extrastorage:neural_processor>, <item:refinedstorage:quartz_enriched_iron_block>, <item:refinedstorage:quartz_enriched_iron_block>, <item:refinedstorage:quartz_enriched_iron_block>, <item:refinedstorage:quartz_enriched_iron_block>, <item:refinedstorage:quartz_enriched_iron_block>, <item:extrastorage:neural_processor>, <item:extrastorage:neural_processor>], 
	[<item:extrastorage:neural_processor>, <item:extrastorage:neural_processor>, <item:minecraft:redstone_block>, <item:minecraft:redstone_block>, <item:minecraft:redstone_block>, <item:minecraft:redstone_block>, <item:minecraft:redstone_block>, <item:extrastorage:neural_processor>, <item:extrastorage:neural_processor>], 
	[<item:refinedstorage:quartz_enriched_iron_block>, <item:minecraft:redstone_block>, <tag:items:refinedstorage:disks/items/16384k>, <tag:items:refinedstorage:disks/items/16384k>, <tag:items:refinedstorage:disks/items/16384k>, <tag:items:refinedstorage:disks/items/16384k>, <tag:items:refinedstorage:disks/items/16384k>, <item:minecraft:redstone_block>, <item:refinedstorage:quartz_enriched_iron_block>], 
	[<item:refinedstorage:quartz_enriched_iron_block>, <item:minecraft:redstone_block>, <tag:items:refinedstorage:disks/items/16384k>, <item:mysticalagradditions:creative_essence>, <item:storagedrawers:creative_storage_upgrade>, <item:mysticalagradditions:creative_essence>, <tag:items:refinedstorage:disks/items/16384k>, <item:minecraft:redstone_block>, <item:refinedstorage:quartz_enriched_iron_block>], 
	[<item:refinedstorage:quartz_enriched_iron_block>, <item:minecraft:redstone_block>, <tag:items:refinedstorage:disks/items/16384k>, <item:storagedrawers:creative_storage_upgrade>, <item:extendedcrafting:ultimate_singularity>, <item:storagedrawers:creative_storage_upgrade>, <tag:items:refinedstorage:disks/items/16384k>, <item:minecraft:redstone_block>, <item:refinedstorage:quartz_enriched_iron_block>], 
	[<item:refinedstorage:quartz_enriched_iron_block>, <item:minecraft:redstone_block>, <tag:items:refinedstorage:disks/items/16384k>, <item:mysticalagradditions:creative_essence>, <item:storagedrawers:creative_storage_upgrade>, <item:mysticalagradditions:creative_essence>, <tag:items:refinedstorage:disks/items/16384k>, <item:minecraft:redstone_block>, <item:refinedstorage:quartz_enriched_iron_block>], 
	[<item:refinedstorage:quartz_enriched_iron_block>, <item:minecraft:redstone_block>, <tag:items:refinedstorage:disks/items/16384k>, <tag:items:refinedstorage:disks/items/16384k>, <tag:items:refinedstorage:disks/items/16384k>, <tag:items:refinedstorage:disks/items/16384k>, <tag:items:refinedstorage:disks/items/16384k>, <item:minecraft:redstone_block>, <item:refinedstorage:quartz_enriched_iron_block>], 
	[<item:extrastorage:neural_processor>, <item:extrastorage:neural_processor>, <item:minecraft:redstone_block>, <item:minecraft:redstone_block>, <item:minecraft:redstone_block>, <item:minecraft:redstone_block>, <item:minecraft:redstone_block>, <item:extrastorage:neural_processor>, <item:extrastorage:neural_processor>], 
	[<item:extrastorage:neural_processor>, <item:extrastorage:neural_processor>, <item:refinedstorage:quartz_enriched_iron_block>, <item:refinedstorage:quartz_enriched_iron_block>, <item:refinedstorage:quartz_enriched_iron_block>, <item:refinedstorage:quartz_enriched_iron_block>, <item:refinedstorage:quartz_enriched_iron_block>, <item:extrastorage:neural_processor>, <item:extrastorage:neural_processor>]
]);
mods.extendedcrafting.TableCrafting.addShaped("infinite_fluid_storage_disk_custom", 0, <item:refinedstorage:creative_fluid_storage_disk>, [
	[<item:extrastorage:neural_processor>, <item:extrastorage:neural_processor>, <item:refinedstorage:quartz_enriched_iron_block>, <item:refinedstorage:quartz_enriched_iron_block>, <item:refinedstorage:quartz_enriched_iron_block>, <item:refinedstorage:quartz_enriched_iron_block>, <item:refinedstorage:quartz_enriched_iron_block>, <item:extrastorage:neural_processor>, <item:extrastorage:neural_processor>], 
	[<item:extrastorage:neural_processor>, <item:extrastorage:neural_processor>, <item:minecraft:redstone_block>, <item:minecraft:redstone_block>, <item:minecraft:redstone_block>, <item:minecraft:redstone_block>, <item:minecraft:redstone_block>, <item:extrastorage:neural_processor>, <item:extrastorage:neural_processor>], 
	[<item:refinedstorage:quartz_enriched_iron_block>, <item:minecraft:redstone_block>, <tag:items:refinedstorage:disks/fluids/16384k>, <tag:items:refinedstorage:disks/fluids/16384k>, <tag:items:refinedstorage:disks/fluids/16384k>, <tag:items:refinedstorage:disks/fluids/16384k>, <tag:items:refinedstorage:disks/fluids/16384k>, <item:minecraft:redstone_block>, <item:refinedstorage:quartz_enriched_iron_block>], 
	[<item:refinedstorage:quartz_enriched_iron_block>, <item:minecraft:redstone_block>, <tag:items:refinedstorage:disks/fluids/16384k>, <item:mysticalagradditions:creative_essence>, <item:storagedrawers:creative_storage_upgrade>, <item:mysticalagradditions:creative_essence>, <tag:items:refinedstorage:disks/fluids/16384k>, <item:minecraft:redstone_block>, <item:refinedstorage:quartz_enriched_iron_block>], 
	[<item:refinedstorage:quartz_enriched_iron_block>, <item:minecraft:redstone_block>, <tag:items:refinedstorage:disks/fluids/16384k>, <item:storagedrawers:creative_storage_upgrade>, <item:extendedcrafting:ultimate_singularity>, <item:storagedrawers:creative_storage_upgrade>, <tag:items:refinedstorage:disks/fluids/16384k>, <item:minecraft:redstone_block>, <item:refinedstorage:quartz_enriched_iron_block>], 
	[<item:refinedstorage:quartz_enriched_iron_block>, <item:minecraft:redstone_block>, <tag:items:refinedstorage:disks/fluids/16384k>, <item:mysticalagradditions:creative_essence>, <item:storagedrawers:creative_storage_upgrade>, <item:mysticalagradditions:creative_essence>, <tag:items:refinedstorage:disks/fluids/16384k>, <item:minecraft:redstone_block>, <item:refinedstorage:quartz_enriched_iron_block>], 
	[<item:refinedstorage:quartz_enriched_iron_block>, <item:minecraft:redstone_block>, <tag:items:refinedstorage:disks/fluids/16384k>, <tag:items:refinedstorage:disks/fluids/16384k>, <tag:items:refinedstorage:disks/fluids/16384k>, <tag:items:refinedstorage:disks/fluids/16384k>, <tag:items:refinedstorage:disks/fluids/16384k>, <item:minecraft:redstone_block>, <item:refinedstorage:quartz_enriched_iron_block>], 
	[<item:extrastorage:neural_processor>, <item:extrastorage:neural_processor>, <item:minecraft:redstone_block>, <item:minecraft:redstone_block>, <item:minecraft:redstone_block>, <item:minecraft:redstone_block>, <item:minecraft:redstone_block>, <item:extrastorage:neural_processor>, <item:extrastorage:neural_processor>], 
	[<item:extrastorage:neural_processor>, <item:extrastorage:neural_processor>, <item:refinedstorage:quartz_enriched_iron_block>, <item:refinedstorage:quartz_enriched_iron_block>, <item:refinedstorage:quartz_enriched_iron_block>, <item:refinedstorage:quartz_enriched_iron_block>, <item:refinedstorage:quartz_enriched_iron_block>, <item:extrastorage:neural_processor>, <item:extrastorage:neural_processor>]
]);
mods.extendedcrafting.TableCrafting.addShaped("creative_pool", 0, <item:botania:creative_pool>, [
	[<item:botania:gaia_ingot>, <item:botania:elementium_ingot>, <item:botania:dragonstone>, <item:botania:pixie_dust>, <item:botania:quartz_elven>, <item:botania:pixie_dust>, <item:botania:dragonstone>, <item:botania:elementium_ingot>, <item:botania:gaia_ingot>], 
	[<item:botania:elementium_ingot>, <item:botania:terrasteel_block>, <item:botania:terrasteel_block>, <item:botania:terrasteel_block>, <item:botania:terrasteel_block>, <item:botania:terrasteel_block>, <item:botania:terrasteel_block>, <item:botania:terrasteel_block>, <item:botania:elementium_ingot>], 
	[<item:botania:dragonstone>, <item:botania:terrasteel_block>, <item:botania:rune_spring>, <item:botania:rune_greed>, <item:botania:rune_water>, <item:botania:rune_gluttony>, <item:botania:rune_winter>, <item:botania:terrasteel_block>, <item:botania:dragonstone>], 
	[<item:botania:pixie_dust>, <item:botania:terrasteel_block>, <item:botania:rune_sloth>, <item:mysticalagradditions:creative_essence>, <item:extendedcrafting:the_ultimate_ingot>, <item:mysticalagradditions:creative_essence>, <item:botania:rune_mana>, <item:botania:terrasteel_block>, <item:botania:pixie_dust>], 
	[<item:botania:quartz_elven>, <item:botania:terrasteel_block>, <item:botania:rune_fire>, <item:extendedcrafting:the_ultimate_ingot>, <item:extendedcrafting:ultimate_singularity>, <item:extendedcrafting:the_ultimate_ingot>, <item:botania:rune_earth>, <item:botania:terrasteel_block>, <item:botania:quartz_elven>], 
	[<item:botania:pixie_dust>, <item:botania:terrasteel_block>, <item:botania:rune_wrath>, <item:mysticalagradditions:creative_essence>, <item:extendedcrafting:the_ultimate_ingot>, <item:mysticalagradditions:creative_essence>, <item:botania:rune_pride>, <item:botania:terrasteel_block>, <item:botania:pixie_dust>], 
	[<item:botania:dragonstone>, <item:botania:terrasteel_block>, <item:botania:rune_autumn>, <item:botania:rune_envy>, <item:botania:rune_air>, <item:botania:rune_lust>, <item:botania:rune_summer>, <item:botania:terrasteel_block>, <item:botania:dragonstone>], 
	[<item:botania:elementium_ingot>, <item:botania:terrasteel_block>, <item:botania:terrasteel_block>, <item:botania:terrasteel_block>, <item:botania:terrasteel_block>, <item:botania:terrasteel_block>, <item:botania:terrasteel_block>, <item:botania:terrasteel_block>, <item:botania:elementium_ingot>], 
	[<item:botania:gaia_ingot>, <item:botania:elementium_ingot>, <item:botania:dragonstone>, <item:botania:pixie_dust>, <item:botania:quartz_elven>, <item:botania:pixie_dust>, <item:botania:dragonstone>, <item:botania:elementium_ingot>, <item:botania:gaia_ingot>]
]);
mods.extendedcrafting.TableCrafting.addShaped("machine_efficiency_creative_augment", 0, <item:thermal:machine_efficiency_creative_augment>, [
	[<item:thermal:machine_efficiency_augment>, <item:thermal:machine_efficiency_augment>, <item:thermal:machine_efficiency_augment>, <item:thermal:machine_efficiency_augment>, <item:thermal:machine_efficiency_augment>, <item:thermal:machine_efficiency_augment>, <item:thermal:machine_efficiency_augment>, <item:thermal:machine_efficiency_augment>, <item:thermal:machine_efficiency_augment>], 
	[<item:thermal:machine_efficiency_augment>, <item:thermal:machine_speed_augment>, <item:thermal:machine_speed_augment>, <item:thermal:machine_speed_augment>, <item:thermal:machine_speed_augment>, <item:thermal:machine_speed_augment>, <item:thermal:machine_speed_augment>, <item:thermal:machine_speed_augment>, <item:thermal:machine_efficiency_augment>], 
	[<item:thermal:machine_efficiency_augment>, <item:thermal:machine_speed_augment>, <item:thermal:rf_coil>, <item:thermal:rf_coil>, <item:thermal:rf_coil>, <item:thermal:rf_coil>, <item:thermal:rf_coil>, <item:thermal:machine_speed_augment>, <item:thermal:machine_efficiency_augment>], 
	[<item:thermal:machine_efficiency_augment>, <item:thermal:machine_speed_augment>, <item:thermal:upgrade_augment_3>, <tag:items:forge:ingots/constantan>, <item:extendedcrafting:the_ultimate_ingot>, <tag:items:forge:ingots/signalum>, <item:thermal:upgrade_augment_3>, <item:thermal:machine_speed_augment>, <item:thermal:machine_efficiency_augment>], 
	[<item:thermal:machine_efficiency_augment>, <item:thermal:machine_speed_augment>, <item:thermal:upgrade_augment_3>, <tag:items:forge:ingots/bronze>, <item:extendedcrafting:ultimate_singularity>, <tag:items:forge:ingots/lumium>, <item:thermal:upgrade_augment_3>, <item:thermal:machine_speed_augment>, <item:thermal:machine_efficiency_augment>], 
	[<item:thermal:machine_efficiency_augment>, <item:thermal:machine_speed_augment>, <item:thermal:upgrade_augment_3>, <tag:items:forge:ingots/electrum>, <tag:items:forge:ingots/invar>, <tag:items:forge:ingots/enderium>, <item:thermal:upgrade_augment_3>, <item:thermal:machine_speed_augment>, <item:thermal:machine_efficiency_augment>], 
	[<item:thermal:machine_efficiency_augment>, <item:thermal:machine_speed_augment>, <item:thermal:redstone_servo>, <item:thermal:redstone_servo>, <item:thermal:redstone_servo>, <item:thermal:redstone_servo>, <item:thermal:redstone_servo>, <item:thermal:machine_speed_augment>, <item:thermal:machine_efficiency_augment>], 
	[<item:thermal:machine_efficiency_augment>, <item:thermal:machine_speed_augment>, <item:thermal:machine_speed_augment>, <item:thermal:machine_speed_augment>, <item:thermal:machine_speed_augment>, <item:thermal:machine_speed_augment>, <item:thermal:machine_speed_augment>, <item:thermal:machine_speed_augment>, <item:thermal:machine_efficiency_augment>], 
	[<item:thermal:machine_efficiency_augment>, <item:thermal:machine_efficiency_augment>, <item:thermal:machine_efficiency_augment>, <item:thermal:machine_efficiency_augment>, <item:thermal:machine_efficiency_augment>, <item:thermal:machine_efficiency_augment>, <item:thermal:machine_efficiency_augment>, <item:thermal:machine_efficiency_augment>, <item:thermal:machine_efficiency_augment>]
]);
mods.extendedcrafting.TableCrafting.addShaped("creative_controller", 0, <item:refinedstorage:creative_controller>, [
	[<item:mekanismgenerators:fusion_reactor_frame>, <item:mekanismgenerators:fusion_reactor_frame>, <item:mekanismgenerators:reactor_glass>, <item:solarflux:sp_8>, <item:mekanismgenerators:reactor_glass>, <item:mekanismgenerators:fusion_reactor_frame>, <item:mekanismgenerators:fusion_reactor_frame>], 
	[<item:mekanismgenerators:fusion_reactor_frame>, <item:powah:energy_cell_nitro>, <item:refinedstorage:machine_casing>, <item:mekanism:ultimate_energy_cube>.withTag({mekData: {EnergyContainers: [{Container: 0 as byte, stored: "256000000" as string}]}}), <item:refinedstorage:machine_casing>, <item:powah:energy_cell_nitro>, <item:mekanismgenerators:fusion_reactor_frame>], 
	[<item:mekanismgenerators:reactor_glass>, <item:refinedstorage:machine_casing>, <item:refinedstorage:quartz_enriched_iron_block>, <item:mysticalagradditions:creative_essence>, <item:refinedstorage:quartz_enriched_iron_block>, <item:refinedstorage:machine_casing>, <item:mekanismgenerators:reactor_glass>], 
	[<item:powah:solar_panel_nitro>, <item:mekanism:ultimate_energy_cube>.withTag({mekData: {EnergyContainers: [{Container: 0 as byte, stored: "256000000" as string}]}}), <item:extendedcrafting:the_ultimate_ingot>, <item:extendedcrafting:ultimate_singularity>, <item:extendedcrafting:the_ultimate_ingot>, <item:mekanism:ultimate_energy_cube>.withTag({mekData: {EnergyContainers: [{Container: 0 as byte, stored: "256000000" as string}]}}), <item:powah:solar_panel_nitro>], 
	[<item:mekanismgenerators:reactor_glass>, <item:refinedstorage:machine_casing>, <item:refinedstorage:quartz_enriched_iron_block>, <item:mysticalagradditions:creative_essence>, <item:refinedstorage:quartz_enriched_iron_block>, <item:refinedstorage:machine_casing>, <item:mekanismgenerators:reactor_glass>], 
	[<item:mekanismgenerators:fusion_reactor_frame>, <item:powah:energy_cell_nitro>, <item:refinedstorage:machine_casing>, <item:mekanism:ultimate_energy_cube>.withTag({mekData: {EnergyContainers: [{Container: 0 as byte, stored: "256000000" as string}]}}), <item:refinedstorage:machine_casing>, <item:powah:energy_cell_nitro>, <item:mekanismgenerators:fusion_reactor_frame>], 
	[<item:mekanismgenerators:fusion_reactor_frame>, <item:mekanismgenerators:fusion_reactor_frame>, <item:mekanismgenerators:reactor_glass>, <item:solarflux:sp_8>, <item:mekanismgenerators:reactor_glass>, <item:mekanismgenerators:fusion_reactor_frame>, <item:mekanismgenerators:fusion_reactor_frame>]
]);
mods.extendedcrafting.TableCrafting.addShaped("creative_motor", 0, <item:create:creative_motor>, [
	[<item:create:refined_radiance_casing>, <tag:items:forge:ingots/brass>, <item:extendedcrafting:crystaltine_ingot>, <item:create:precision_mechanism>, <item:create:radial_chassis>, <item:create:precision_mechanism>, <item:extendedcrafting:crystaltine_ingot>, <tag:items:forge:ingots/brass>, <item:create:refined_radiance_casing>], 
	[<tag:items:forge:ingots/brass>, <item:create:shadow_steel_casing>, <item:create:cogwheel>, <item:create:belt_connector>, <item:create:shaft>, <item:create:belt_connector>, <item:create:cogwheel>, <item:create:shadow_steel_casing>, <tag:items:forge:ingots/brass>], 
	[<item:extendedcrafting:crystaltine_ingot>, <item:create:cogwheel>, <item:create:large_cogwheel>, <item:create:rotation_speed_controller>, <item:create:large_cogwheel>, <item:create:rotation_speed_controller>, <item:create:large_cogwheel>, <item:create:cogwheel>, <item:extendedcrafting:crystaltine_ingot>], 
	[<item:create:precision_mechanism>, <item:create:belt_connector>, <item:create:rotation_speed_controller>, <item:mysticalagradditions:creative_essence>, <item:extendedcrafting:the_ultimate_ingot>, <item:mysticalagradditions:creative_essence>, <item:create:rotation_speed_controller>, <item:create:belt_connector>, <item:create:precision_mechanism>], 
	[<item:create:radial_chassis>, <item:create:shaft>, <item:create:large_cogwheel>, <item:extendedcrafting:the_ultimate_ingot>, <item:extendedcrafting:ultimate_singularity>, <item:extendedcrafting:the_ultimate_ingot>, <item:create:large_cogwheel>, <item:create:shaft>, <item:create:radial_chassis>], 
	[<item:create:precision_mechanism>, <item:create:belt_connector>, <item:create:rotation_speed_controller>, <item:mysticalagradditions:creative_essence>, <item:extendedcrafting:the_ultimate_ingot>, <item:mysticalagradditions:creative_essence>, <item:create:rotation_speed_controller>, <item:create:belt_connector>, <item:create:precision_mechanism>], 
	[<item:extendedcrafting:crystaltine_ingot>, <item:create:cogwheel>, <item:create:large_cogwheel>, <item:create:rotation_speed_controller>, <item:create:large_cogwheel>, <item:create:rotation_speed_controller>, <item:create:large_cogwheel>, <item:create:cogwheel>, <item:extendedcrafting:crystaltine_ingot>], 
	[<tag:items:forge:ingots/brass>, <item:create:shadow_steel_casing>, <item:create:cogwheel>, <item:create:belt_connector>, <item:create:shaft>, <item:create:belt_connector>, <item:create:cogwheel>, <item:create:shadow_steel_casing>, <tag:items:forge:ingots/brass>], 
	[<item:create:refined_radiance_casing>, <tag:items:forge:ingots/brass>, <item:extendedcrafting:crystaltine_ingot>, <item:create:precision_mechanism>, <item:create:radial_chassis>, <item:create:precision_mechanism>, <item:extendedcrafting:crystaltine_ingot>, <tag:items:forge:ingots/brass>, <item:create:refined_radiance_casing>]
]);
mods.extendedcrafting.TableCrafting.addShaped("create/creative_crate", 0, <item:create:creative_crate>, [
	[<item:mekanismgenerators:fusion_reactor_frame>, <item:mekanismgenerators:fusion_reactor_frame>, <item:mekanismgenerators:reactor_glass>, <item:mekanismgenerators:reactor_glass>, <item:mekanismgenerators:reactor_glass>, <item:mekanismgenerators:reactor_glass>, <item:mekanismgenerators:reactor_glass>, <item:mekanismgenerators:fusion_reactor_frame>, <item:mekanismgenerators:fusion_reactor_frame>], 
	[<item:mekanismgenerators:fusion_reactor_frame>, <item:extendedcrafting:the_ultimate_ingot>, <item:mysticalagradditions:creative_essence>, <item:extendedcrafting:crystaltine_catalyst>, <item:extendedcrafting:enhanced_ender_catalyst>, <item:extendedcrafting:crystaltine_catalyst>, <item:mysticalagradditions:creative_essence>, <item:extendedcrafting:the_ultimate_ingot>, <item:mekanismgenerators:fusion_reactor_frame>], 
	[<item:mekanismgenerators:reactor_glass>, <item:mysticalagradditions:creative_essence>, <item:refinedstorage:creative_controller>, <item:extendedcrafting:the_ultimate_ingot>, <item:thermal:machine_efficiency_creative_augment>, <item:extendedcrafting:the_ultimate_ingot>, <item:mekanism:creative_energy_cube>.withTag({mekData: {EnergyContainers: [{Container: 0 as byte, stored: "18446744073709551615.9999" as string}]}}), <item:mysticalagradditions:creative_essence>, <item:mekanismgenerators:reactor_glass>], 
	[<item:mekanismgenerators:reactor_glass>, <item:extendedcrafting:crystaltine_catalyst>, <item:extendedcrafting:the_ultimate_ingot>, <tag:items:crafttweaker:dimension_cards>, <item:simplyjetpacks:jetpack_creative_armored>, <item:inventorypets:pet_illuminati>, <item:extendedcrafting:the_ultimate_ingot>, <item:extendedcrafting:crystaltine_catalyst>, <item:mekanismgenerators:reactor_glass>], 
	[<item:mekanismgenerators:reactor_glass>, <item:extendedcrafting:enhanced_ender_catalyst>, <item:botania:creative_pool>, <item:extendedcrafting:ultimate_singularity>, <item:projecte:watch_of_flowing_time>, <item:extendedcrafting:ultimate_singularity>, <item:create:creative_motor>, <item:extendedcrafting:enhanced_ender_catalyst>, <item:mekanismgenerators:reactor_glass>], 
	[<item:mekanismgenerators:reactor_glass>, <item:extendedcrafting:crystaltine_catalyst>, <item:extendedcrafting:the_ultimate_ingot>, <item:mekanism:creative_fluid_tank>, <item:create:creative_blaze_cake>, <item:mekanism:creative_chemical_tank>, <item:extendedcrafting:the_ultimate_ingot>, <item:extendedcrafting:crystaltine_catalyst>, <item:mekanismgenerators:reactor_glass>], 
	[<item:mekanismgenerators:reactor_glass>, <item:mysticalagradditions:creative_essence>, <item:refinedstorage:creative_fluid_storage_disk>, <item:extendedcrafting:the_ultimate_ingot>, <item:creativecrafter:creative_crafter>, <item:extendedcrafting:the_ultimate_ingot>, <item:refinedstorage:creative_storage_disk>, <item:mysticalagradditions:creative_essence>, <item:mekanismgenerators:reactor_glass>], 
	[<item:mekanismgenerators:fusion_reactor_frame>, <item:extendedcrafting:the_ultimate_ingot>, <item:mysticalagradditions:creative_essence>, <item:extendedcrafting:crystaltine_catalyst>, <item:extendedcrafting:enhanced_ender_catalyst>, <item:extendedcrafting:crystaltine_catalyst>, <item:mysticalagradditions:creative_essence>, <item:extendedcrafting:the_ultimate_ingot>, <item:mekanismgenerators:fusion_reactor_frame>], 
	[<item:mekanismgenerators:fusion_reactor_frame>, <item:mekanismgenerators:fusion_reactor_frame>, <item:mekanismgenerators:reactor_glass>, <item:mekanismgenerators:reactor_glass>, <item:mekanismgenerators:reactor_glass>, <item:mekanismgenerators:reactor_glass>, <item:mekanismgenerators:reactor_glass>, <item:mekanismgenerators:fusion_reactor_frame>, <item:mekanismgenerators:fusion_reactor_frame>]
]);
craftingTable.removeByName("rsinfinitybooster:infinity_card");
mods.extendedcrafting.TableCrafting.addShaped("infinity_card", 0, <item:rsinfinitybooster:infinity_card>, [
	[<item:minecraft:nether_star>, <item:minecraft:ender_eye>, <item:minecraft:netherite_ingot>, <item:minecraft:netherite_ingot>, <item:minecraft:netherite_ingot>, <item:minecraft:netherite_ingot>, <item:minecraft:netherite_ingot>, <item:minecraft:ender_eye>, <item:minecraft:nether_star>], 
	[<item:minecraft:ender_eye>, <tag:items:crafttweaker:wireless_range_boosters>, <tag:items:crafttweaker:wireless_range_boosters>, <tag:items:crafttweaker:wireless_range_boosters>, <tag:items:crafttweaker:wireless_range_boosters>, <tag:items:crafttweaker:wireless_range_boosters>, <tag:items:crafttweaker:wireless_range_boosters>, <tag:items:crafttweaker:wireless_range_boosters>, <item:minecraft:ender_eye>], 
	[<item:minecraft:netherite_ingot>, <tag:items:crafttweaker:wireless_range_boosters>, <tag:items:crafttweaker:wireless_range_boosters>, <tag:items:crafttweaker:wireless_range_boosters>, <tag:items:crafttweaker:wireless_range_boosters>, <tag:items:crafttweaker:wireless_range_boosters>, <tag:items:crafttweaker:wireless_range_boosters>, <tag:items:crafttweaker:wireless_range_boosters>, <item:minecraft:netherite_ingot>], 
	[<item:minecraft:netherite_ingot>, <tag:items:crafttweaker:wireless_range_boosters>, <tag:items:crafttweaker:wireless_range_boosters>, <item:mysticalagradditions:creative_essence>, <item:extendedcrafting:the_ultimate_ingot>, <item:mysticalagradditions:creative_essence>, <tag:items:crafttweaker:wireless_range_boosters>, <tag:items:crafttweaker:wireless_range_boosters>, <item:minecraft:netherite_ingot>], 
	[<item:minecraft:netherite_ingot>, <tag:items:crafttweaker:wireless_range_boosters>, <tag:items:crafttweaker:wireless_range_boosters>, <item:extendedcrafting:the_ultimate_ingot>, <item:extendedcrafting:ultimate_singularity>, <item:extendedcrafting:the_ultimate_ingot>, <tag:items:crafttweaker:wireless_range_boosters>, <tag:items:crafttweaker:wireless_range_boosters>, <item:minecraft:netherite_ingot>], 
	[<item:minecraft:netherite_ingot>, <tag:items:crafttweaker:wireless_range_boosters>, <tag:items:crafttweaker:wireless_range_boosters>, <item:mysticalagradditions:creative_essence>, <item:extendedcrafting:the_ultimate_ingot>, <item:mysticalagradditions:creative_essence>, <tag:items:crafttweaker:wireless_range_boosters>, <tag:items:crafttweaker:wireless_range_boosters>, <item:minecraft:netherite_ingot>], 
	[<item:minecraft:netherite_ingot>, <tag:items:crafttweaker:wireless_range_boosters>, <tag:items:crafttweaker:wireless_range_boosters>, <tag:items:crafttweaker:wireless_range_boosters>, <tag:items:crafttweaker:wireless_range_boosters>, <tag:items:crafttweaker:wireless_range_boosters>, <tag:items:crafttweaker:wireless_range_boosters>, <tag:items:crafttweaker:wireless_range_boosters>, <item:minecraft:netherite_ingot>], 
	[<item:minecraft:ender_eye>, <tag:items:crafttweaker:wireless_range_boosters>, <tag:items:crafttweaker:wireless_range_boosters>, <tag:items:crafttweaker:wireless_range_boosters>, <tag:items:crafttweaker:wireless_range_boosters>, <tag:items:crafttweaker:wireless_range_boosters>, <tag:items:crafttweaker:wireless_range_boosters>, <tag:items:crafttweaker:wireless_range_boosters>, <item:minecraft:ender_eye>], 
	[<item:minecraft:nether_star>, <item:minecraft:ender_eye>, <item:minecraft:netherite_ingot>, <item:minecraft:netherite_ingot>, <item:minecraft:netherite_ingot>, <item:minecraft:netherite_ingot>, <item:minecraft:netherite_ingot>, <item:minecraft:ender_eye>, <item:minecraft:nether_star>]
]);
craftingTable.removeByName("rsinfinitybooster:dimension_card");
mods.extendedcrafting.TableCrafting.addShaped("dimension_card", 0, <item:rsinfinitybooster:dimension_card>, [
	[<item:silentgear:azure_silver_ingot>, <item:silentgear:azure_silver_ingot>, <item:silentgear:azure_silver_ingot>, <item:silentgear:azure_silver_ingot>, <item:silentgear:azure_silver_ingot>, <item:silentgear:azure_silver_ingot>, <item:silentgear:azure_silver_ingot>, <item:silentgear:azure_silver_ingot>, <item:silentgear:azure_silver_ingot>], 
	[<item:silentgear:azure_silver_ingot>, <item:minecraft:nether_star>, <item:minecraft:nether_star>, <item:minecraft:nether_star>, <item:minecraft:nether_star>, <item:minecraft:nether_star>, <item:minecraft:nether_star>, <item:minecraft:nether_star>, <item:silentgear:azure_silver_ingot>], 
	[<item:silentgear:azure_silver_ingot>, <item:minecraft:nether_star>, <item:minecraft:diamond>, <item:minecraft:diamond>, <item:minecraft:diamond>, <item:minecraft:diamond>, <item:minecraft:diamond>, <item:minecraft:nether_star>, <item:silentgear:azure_silver_ingot>], 
	[<item:silentgear:azure_silver_ingot>, <item:minecraft:nether_star>, <item:minecraft:diamond>, <item:mysticalagradditions:creative_essence>, <item:rsinfinitybooster:infinity_card>, <item:extendedcrafting:the_ultimate_ingot>, <item:minecraft:diamond>, <item:minecraft:nether_star>, <item:silentgear:azure_silver_ingot>], 
	[<item:silentgear:azure_silver_ingot>, <item:minecraft:nether_star>, <item:minecraft:diamond>, <item:rsinfinitybooster:infinity_card>, <item:extendedcrafting:ultimate_singularity>, <item:rsinfinitybooster:infinity_card>, <item:minecraft:diamond>, <item:minecraft:nether_star>, <item:silentgear:azure_silver_ingot>], 
	[<item:silentgear:azure_silver_ingot>, <item:minecraft:nether_star>, <item:minecraft:diamond>, <item:extendedcrafting:the_ultimate_ingot>, <item:rsinfinitybooster:infinity_card>, <item:mysticalagradditions:creative_essence>, <item:minecraft:diamond>, <item:minecraft:nether_star>, <item:silentgear:azure_silver_ingot>], 
	[<item:silentgear:azure_silver_ingot>, <item:minecraft:nether_star>, <item:minecraft:diamond>, <item:minecraft:diamond>, <item:minecraft:diamond>, <item:minecraft:diamond>, <item:minecraft:diamond>, <item:minecraft:nether_star>, <item:silentgear:azure_silver_ingot>], 
	[<item:silentgear:azure_silver_ingot>, <item:minecraft:nether_star>, <item:minecraft:nether_star>, <item:minecraft:nether_star>, <item:minecraft:nether_star>, <item:minecraft:nether_star>, <item:minecraft:nether_star>, <item:minecraft:nether_star>, <item:silentgear:azure_silver_ingot>], 
	[<item:silentgear:azure_silver_ingot>, <item:silentgear:azure_silver_ingot>, <item:silentgear:azure_silver_ingot>, <item:silentgear:azure_silver_ingot>, <item:silentgear:azure_silver_ingot>, <item:silentgear:azure_silver_ingot>, <item:silentgear:azure_silver_ingot>, <item:silentgear:azure_silver_ingot>, <item:silentgear:azure_silver_ingot>]
]);
mods.extendedcrafting.TableCrafting.addShaped("creative_blaze_cake", 0, <item:create:creative_blaze_cake>, [
	[<item:create:blaze_cake_base>, <item:create:blaze_cake_base>, <item:create:blaze_cake>, <item:create:blaze_cake>, <item:create:blaze_cake>, <item:create:blaze_cake>, <item:create:blaze_cake>, <item:create:blaze_cake_base>, <item:create:blaze_cake_base>], 
	[<item:create:blaze_cake_base>, <item:create:blaze_cake_base>, <item:create:blaze_cake>, <item:create:blaze_cake>, <item:create:blaze_cake>, <item:create:blaze_cake>, <item:create:blaze_cake>, <item:create:blaze_cake_base>, <item:create:blaze_cake_base>], 
	[<item:create:blaze_cake>, <item:create:blaze_cake>, <item:create:blaze_burner>, <item:create:blaze_burner>, <item:create:blaze_burner>, <item:create:blaze_burner>, <item:create:blaze_burner>, <item:create:blaze_cake>, <item:create:blaze_cake>], 
	[<item:create:blaze_cake>, <item:create:blaze_cake>, <item:create:blaze_burner>, <item:minecraft:lava_bucket>, <item:mysticalagradditions:creative_essence>, <item:minecraft:lava_bucket>, <item:create:blaze_burner>, <item:create:blaze_cake>, <item:create:blaze_cake>], 
	[<item:create:blaze_cake>, <item:create:blaze_cake>, <item:create:blaze_burner>, <item:mysticalagradditions:creative_essence>, <item:extendedcrafting:ultimate_singularity>, <item:mysticalagradditions:creative_essence>, <item:create:blaze_burner>, <item:create:blaze_cake>, <item:create:blaze_cake>], 
	[<item:create:blaze_cake>, <item:create:blaze_cake>, <item:create:blaze_burner>, <item:minecraft:lava_bucket>, <item:mysticalagradditions:creative_essence>, <item:minecraft:lava_bucket>, <item:create:blaze_burner>, <item:create:blaze_cake>, <item:create:blaze_cake>], 
	[<item:create:blaze_cake>, <item:create:blaze_cake>, <item:create:blaze_burner>, <item:create:blaze_burner>, <item:create:blaze_burner>, <item:create:blaze_burner>, <item:create:blaze_burner>, <item:create:blaze_cake>, <item:create:blaze_cake>], 
	[<item:create:blaze_cake_base>, <item:create:blaze_cake_base>, <item:create:blaze_cake>, <item:create:blaze_cake>, <item:create:blaze_cake>, <item:create:blaze_cake>, <item:create:blaze_cake>, <item:create:blaze_cake_base>, <item:create:blaze_cake_base>], 
	[<item:create:blaze_cake_base>, <item:create:blaze_cake_base>, <item:create:blaze_cake>, <item:create:blaze_cake>, <item:create:blaze_cake>, <item:create:blaze_cake>, <item:create:blaze_cake>, <item:create:blaze_cake_base>, <item:create:blaze_cake_base>]
]);
craftingTable.addShaped("jetpack_creative",  <item:simplyjetpacks:jetpack_creative>, [
	[<item:extendedcrafting:the_ultimate_ingot>, <item:simplyjetpacks:jetpack_vanilla4>, <item:extendedcrafting:the_ultimate_ingot>], 
	[<item:simplyjetpacks:jetpack_mek4>, <item:mekanism:jetpack>, <item:simplyjetpacks:jetpack_te4>], 
	[<item:extendedcrafting:the_ultimate_ingot>, <item:simplyjetpacks:jetpack_ie3>, <item:extendedcrafting:the_ultimate_ingot>]
]);
craftingTable.addShaped("jetpack_creative_armored", <item:simplyjetpacks:jetpack_creative_armored>, [
	[<item:simplyjetpacks:armorplating_mek4>, <item:mekanism:jetpack_armored>, <item:simplyjetpacks:armorplating_te4>], 
	[<item:minecraft:netherite_chestplate>, <item:simplyjetpacks:jetpack_creative>, <item:simplyjetpacks:armorplating_ie3>], 
	[<item:extendedcrafting:the_ultimate_ingot>, <item:immersiveengineering:hammer>, <item:extendedcrafting:the_ultimate_ingot>]
]);
craftingTable.addShapeless("jetpack_creative_armored_to_jetpack_creative", <item:simplyjetpacks:jetpack_creative>, [
	<item:simplyjetpacks:jetpack_creative_armored>
]);
craftingTable.removeByName("projecte:watch_of_flowing_time");
mods.extendedcrafting.TableCrafting.addShaped("projecte.watch_of_flowing_time", <item:projecte:watch_of_flowing_time>, [
	[<item:projecte:red_matter_block>, <item:minecraft:obsidian>, <item:minecraft:obsidian>, <item:minecraft:obsidian>, <item:minecraft:obsidian>, <item:minecraft:obsidian>, <item:projecte:red_matter_block>], 
	[<item:minecraft:obsidian>, <item:extendedcrafting:the_ultimate_ingot>, <item:minecraft:glowstone>, <item:minecraft:glowstone>, <item:minecraft:glowstone>, <item:extendedcrafting:the_ultimate_ingot>, <item:minecraft:obsidian>], 
	[<item:minecraft:obsidian>, <item:minecraft:glowstone>, <item:minecraft:crying_obsidian>, <item:minecraft:clock>.withTag({"quark:clock_calculated": 1 as byte}), <item:minecraft:crying_obsidian>, <item:minecraft:glowstone>, <item:minecraft:obsidian>], 
	[<item:minecraft:obsidian>, <item:minecraft:glowstone>, <item:minecraft:crying_obsidian>, <item:extendedcrafting:ultimate_singularity>, <item:minecraft:crying_obsidian>, <item:minecraft:glowstone>, <item:minecraft:obsidian>], 
	[<item:minecraft:obsidian>, <item:minecraft:glowstone>, <item:minecraft:crying_obsidian>, <item:minecraft:clock>.withTag({"quark:clock_calculated": 1 as byte}), <item:minecraft:crying_obsidian>, <item:minecraft:glowstone>, <item:minecraft:obsidian>], 
	[<item:minecraft:obsidian>, <item:extendedcrafting:the_ultimate_ingot>, <item:minecraft:glowstone>, <item:minecraft:glowstone>, <item:minecraft:glowstone>, <item:extendedcrafting:the_ultimate_ingot>, <item:minecraft:obsidian>], 
	[<item:projecte:red_matter_block>, <item:minecraft:obsidian>, <item:minecraft:obsidian>, <item:minecraft:obsidian>, <item:minecraft:obsidian>, <item:minecraft:obsidian>, <item:projecte:red_matter_block>]
]);